### ISSUE TITLE
Updating site with new details 

### ISSUE THREAD

**Issue by mbj36** [smvdu/sfd-smvdu#69]
According to the proposal, we need a volunteer who can update the site with new details

- [x] Editing all the new details. i.e - Date, Updating 'about' section

- [x] Updating Event schedule 

here is the proposal - 
[sfd16.pdf](https://github.com/smvdu/sfd-smvdu/files/440160/sfd16.pdf)

**Comment by mbj36** [comment]
@shivamluthra Are you interested ?

**Comment by shivamluthra** [comment]
Yes sir, i am up for it!

**Comment by mbj36** [comment]
@shivamluthra Go ahead
