### ISSUE TITLE
Adding timer to the website

### ISSUE THREAD

**Issue by mbj36** [smvdu/sfd-smvdu#70]
Work need to be done 
- Adding timer to website just above the register button. U just have to calculate the time and un-comment the timer code written in source code
- Removing Dell Logo 
- Un-commenting the Slides popup till we start our event

**Comment by shivamluthra** [comment]
:+1:

**Comment by mbj36** [comment]
@shivamluthra If u are interested for taking up more than one issue,  make sure you make seperate pull requests for each issue and please do it ASAP
