### ISSUE TITLE
Activate Firebase for 'new' registration

### ISSUE THREAD

**Issue by mbj36** [smvdu/sfd-smvdu#71]
For help  - https://www.firebase.com/

**Comment by mbj36** [comment]
@rusrushal13 Are you up for it ?

**Comment by rusrushal13** [comment]
Actaully I am reading about the firebase from 1-2 sources but I still can't get it how to integrate Firebase into registration based?
I am reading from these resources(may you could suggest something else):
1. https://codelabs.developers.google.com/codelabs/firebase-web/#0
2. https://github.com/srookhuizen/registration

**Comment by mbj36** [comment]
Just look into the code of main.js file, u will find firebase link there and best resource to learn about it  -  https://www.firebase.com/ @rusrushal13
