### ISSUE TITLE
Potential EULA violation

### ISSUE THREAD

**Issue by fontpolice** [smvdu/sfd-smvdu#74]
Dear smvdu,

It has come to our attention through [FontFinder](http://www.fontfinder.io) that your hosting of stratum-2-web.woff in this public repository might be unintentional.

Sincerely,
The Font Police

**Comment by rishy** [comment]
Guys can you please replace the *stratum-2-web.woff* font with some similar "Open" Font out there? Please have it done on immediate basis.

**Comment by mbj36** [comment]
Done @rishy
